version: "3" # Docker Version


# Which services we will have
services:
  web:
    build:
      context: . 
      dockerfile: django_docker_file
    container_name: django_web
    volumes:
      - ./src:/src
    ports:
      - '8000:8000'
    command: sh -c "python3 manage.py migrate & python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - db_keys.txt
    depends_on:
      - db
      - cache

  db:
    image: postgres:latest
    container_name: my_postgres_db
    env_file:
      - db_keys.txt


  adminer:
    image: adminer:4.7.8
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - '8080:8080'

  cache:
    image: redis:latest
    container_name: my_cache
    depends_on:
      - db

      
